language: php

php:
    - 5.5

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - composer self-update
    - composer install

script:
    - ./vendor/bin/sculpin generate --env=prod --url="https://devdocs.shopware.com"
    - ./contrib/package_plugins.sh
