services:
    shopware_search.index.listener:
        class: Shopware\Devdocs\SearchIndexListener
        arguments:
            - %sculpin.output_dir%
        tags:
            - { name: kernel.event_subscriber }

    webuni.commonmark.tablextension:
        class: Webuni\CommonMark\TableExtension\TableExtension
        tags:
            - { name: sculpin_commonmark.extension }

    shopware_devdocs.twig_extension:
        class: Shopware\Devdocs\TwigExtension
        arguments:
            - @sculpin_theme.theme_twig_extension
            - %kernel.environment%
        tags:
            - { name: twig.extension }
